parallel-jobs = 1
# patches-version = "dev"
# cli-version = "dev"
enable-module-update = true

[ninja-vpn-morphe]
enabled = true 
app-name = "ninja-vpn"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
dpi = "nodpi anydpi auto"
apkpure-dlurl = "ninja-vpn-fast-secure-vpn/app.ninjavpn.android"
