parallel-jobs = 1
# patches-version = "dev"
# cli-version = "dev"
enable-module-update = true

[at4k-launcher-morphe]
enabled = true 
app-name = "at4k-launcher"
rv-brand = "morphe"
build-mode = "apk"
arch = "all"
patches-source = "arandomhooman/hoomans-morphe-patches"
cli-source = "MorpheApp/morphe-cli"
dpi = "nodpi anydpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/cute-little-apps/at4k-launcher-android-tv"
apkpure-dlurl = "https://apkpure.com/at4k-launcher/com.overdevs.at4k"
# apkcombo-dlurl = "https://apkcombo.com/at4k-launcher/com.overdevs.at4k"




