[tiktok-icysymmetra]
enabled = false
app-name = "tiktok"
rv-brand = "icysymmetra"
build-mode = "apk"
arch = "both"
patches-source = "icysymmetra/tiktok-patches-for-morphe"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
archive-dlurl = "https://archive.org/download/geologically/apks/com.zhiliaoapp.musically"
