[fing-paresh]
enabled = true
app-name = "fing"
rv-brand = "paresh"
build-mode = "apk"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://fing-network-tools.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/fing-limited/fing-network-tools"

[proton-vpn-paresh]
enabled = true
app-name = "proton-vpn"
rv-brand = "paresh"
build-mode = "apk"
version = "latest"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"
dpi = "120-640dpi"
prefer-dl-mode = "bundle"

[jiohotstar-paresh]
enabled = true
cli-source = "MorpheApp/morphe-cli"
app-name = "jiohotstar"
rv-brand = "paresh"
build-mode = "apk"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"
apkmirror-dlurl = "https://www.apkmirror.com/apk/jiostar-india-private-limited/jiohotstar-4/"
