enable-module-update = true
patches-version = "dev"

[youtube-morphe-anddea]
enabled = true
app-name = "youtube"
rv-brand = "morphe"
build-mode = "both"
arch = "all"
cli-source = "MorpheApp/morphe-desktop"
patcher-args = "--continue-on-error"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"
[[youtube-morphe-anddea.patches]]
source = "anddea/revanced-patches"
brand = "anddea"
args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/black"

[youtube-music-morphe-anddea]
enabled = true
app-name = "youtube-music"
rv-brand = "morphe"
build-mode = "both"
arch = "both64"
cli-source = "MorpheApp/morphe-desktop"
patcher-args = "--continue-on-error"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"
[[youtube-music-morphe-anddea.patches]]
source = "anddea/revanced-patches"
brand = "anddea"
args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/black"
