enable-module-updates = true
patches-version = "dev"
[speedtest-xtra]
enabled = true
app-name = "speedtest"
rv-brand = "xtra"
build-mode = "apk"
arch = "both64"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://speedtest-net-mobile.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/ookla/speedtest"
dpi = "nodpi anydpi auto"
[[speedtest-xtra.patches]]
source = "BholeyKaBhakt/revanced-patches-xtra"

