
[moonplus-reader-binarymend]
enabled = true
app-name = "moonplus-reader"
rv-brand = "binarymend"
build-mode = "apk"
arch = "all"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://moon-reader.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/moon/moon-reader"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.photos"
dpi = "nodpi anydpi auto"
[[moonplus-reader-binarymend.patches]]
source = "binarymend/morphe-patches"
