enable-module-update = true
patches-version = "dev"
[adobe-acrobat-hooman]
enabled = true
cli-source = "MorpheApp/morphe-cli"
app-name = "adobe-acrobat"
rv-brand = "hooman"
version = "latest"
build-mode = "apk"
uptodown-dlurl = "https://adobe-reader.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/adobe-acrobat/"
dpi = "nodpi anydpi auto"
[[adobe-acrobat-hooman.patches]]
source = "arandomhooman/hoomans-morphe-patches"

[symfonium-hooman]
enabled = true
app-name = "symfonium"
rv-brand = "hooman"
build-mode = "apk"
arch = "all"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://symfonium.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tolriq/symfonium-music-player-cast"
dpi = "nodpi anydpi auto"
[[symfonium-hooman.patches]]
source = "arandomhooman/hoomans-morphe-patches"

[adm-hooman]
enabled = true
app-name = "adm"
rv-brand = "hooman"
build-mode = "apk"
arch = "all"
cli-source = "MorpheApp/morphe-cli"
dpi = "nodpi anydpi auto"
uptodown-dlurl="https://advanced-download-manager.en.uptodown.com/android"
apkmirror-dlurl="https://www.apkmirror.com/apk/admtorrent/advanced-download-manager/"
[[adm-hooman.patches]]
source = "arandomhooman/hoomans-morphe-patches"