enable-module-updates = true
patches-version = "dev"
[gboard-jsonwu1994]
enabled = true
app-name = "gboard"
rv-brand = "jsonwu1994"
build-mode = "apk"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://gboard-go.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard"
dpi = "nodpi anydpi auto"
[[gboard-jsonwu1994.patches]]
source = "jasonwu1994/Gboard-patches"