enable-module-updates = true
patches-version = "dev"
[youtube-morphe]
enabled = true
app-name = "youtube"
rv-brand = "morphe"
build-mode = "both"
version = "21.26.360"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
dpi = "nodpi anydpi auto"
[[youtube-morphe.patches]]
source = "MorpheApp/morphe-patches"
args = "-OdarkThemeBackgroundColor=#000000 "
included-patches = "'Theme'"

[youtube-music-morphe]
enabled = true
app-name = "youtube-music"
rv-brand = "morphe"
build-mode = "both"
arch = "both64"
version = "9.26.51"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
dpi = "nodpi anydpi auto"
[[youtube-music-morphe.patches]]
source = "MorpheApp/morphe-patches"
args = "-OdarkThemeBackgroundColor=#000000 "
included-patches = "'Theme'"
