enable-module-update = true
patches-version = "dev"
[fing-paresh]
enabled = true
app-name = "fing"
rv-brand = "paresh"
build-mode = "apk"
patches-source-host = "gitlab"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://fing-network-tools.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/fing-limited/fing-network-tools"
dpi = "nodpi anydpi auto"
[[fing-paresh.patches]]
source = "Paresh-Maheshwari/paresh-patches"
host = "gitlab"

[proton-vpn-paresh]
enabled = true
app-name = "proton-vpn"
rv-brand = "paresh"
build-mode = "apk"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"
prefer-dl-mode = "bundle"
[[proton-vpn-paresh.patches]]
source = "Paresh-Maheshwari/paresh-patches"
host = "gitlab"

[jiohotstar-paresh]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "jiohotstar"
rv-brand = "paresh"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/jiostar-india-private-limited/jiohotstar-4/"
dpi = "nodpi anydpi auto"
[[jiohotstar-paresh.patches]]
source = "Paresh-Maheshwari/paresh-patches"
host = "gitlab"