enable-module-update = true
patches-version = "dev"
[amazon-india-morphe-rushiranpise]
enabled = true
app-name = "amazon-india"
rv-brand = "morphe"
build-mode = "apk"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://amazon-india.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-india-shop-pay/"
dpi = "nodpi anydpi auto"
[[amazon-india-morphe-rushiranpise.patches]]
source = "rushiranpise/morphe-patches"
included-patches = "'Dark Mode' 'Open Links in Browser'"
excluded-patches = "'Hide Rufus Tab'"
microg-autodetect = "false"
brand = "rushiranpise"
