enable-module-updates = true
patches-version = "dev"
[amazon-india-rushiranpise]
enabled = true
app-name = "amazon-india"
rv-brand = "rushiranpise"
build-mode = "apk"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://amazon-india.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-india-shop-pay/"
dpi = "nodpi anydpi auto"
[[amazon-india-rushiranpise.patches]]
source = "rushiranpise/morphe-patches"
included-patches = "'Dark Mode' 'Open Links in Browser'"
excluded-patches = "'Hide Rufus Tab'"
microg-autodetect = "false"