enable-module-update = true
patches-version = "dev"
[amazon-alexa-signed]
enabled = true
app-name = "amazon-alexa"
rv-brand = "signed"
build-mode = "apk"
cli-source = "apksigner"
cli-source-host = "none"
arch = "all"
prefer-dl-mode = "bundle"
uptodown-dlurl = "https://alexa.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-alexa/"
dpi = "nodpi anydpi auto"
[[amazon-alexa-signed.patches]]
source = "none"
host = "none"
