[disneyplus-morphe-androidtv]
enabled = true 
app-name = "disneyplus"
rv-brand = "morphe-androidtv"
build-mode = "apk"
arch = "all"
patches-source = "ajstrick81/morphe-androidtv-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/disney/disney-android-tv"

[prime-video-morphe-androidtv]
enabled = true 
app-name = "prime-video"
rv-brand = "morphe-androidtv"
build-mode = "apk"
arch = "arm-v7a"
included-patches = "'Clone Prime Video'"
patches-source = "ajstrick81/morphe-androidtv-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi 320dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/prime-video-android-tv-android-tv"

[hbomax-morphe-androidtv]
enabled = true 
app-name = "hbomax"
rv-brand = "morphe-androidtv"
build-mode = "apk"
arch = "all"
patches-source = "ajstrick81/morphe-androidtv-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/warnermedia-direct-llc/max-stream-hbo-tv-movies-android-tv"

[peacock-morphe-androidtv]
enabled = true 
app-name = "peacock"
rv-brand = "morphe-androidtv"
build-mode = "apk"
arch = "all"
patches-source = "ajstrick81/morphe-androidtv-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/peacock-tv-llc/peacock-tv-android-tv"
# apkpure-dlurl = "https://apkpure.com/peacock-tv-stream-tv-movies/com.peacocktv.peacockandroid"
apkcombo-dlurl = "https://apkcombo.com/peacock-tv/com.peacocktv.peacockandroid"

[tubi-morphe-androidtv]
enabled = true 
app-name = "tubi"
rv-brand = "morphe-androidtv"
build-mode = "apk"
arch = "all"
patches-source = "ajstrick81/morphe-androidtv-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tubi-tv/tubi-free-movies-live-tv-android-tv"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.tubitv"

[vix-morphe-androidtv]
enabled = true 
app-name = "vix"
rv-brand = "morphe-androidtv"
build-mode = "apk"
arch = "all"
patches-source = "ajstrick81/morphe-androidtv-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/univision-communications-inc/vix-cine-y-tv-en-espanol-android-tv"

[plutotv-morphe-androidtv]
enabled = true 
app-name = "plutotv"
rv-brand = "morphe-androidtv"
build-mode = "apk"
arch = "all"
patches-source = "ajstrick81/morphe-androidtv-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pluto-inc/pluto-tv-android-tv"
uptodown-dlurl = "https://pluto-tv.en.uptodown.com/android"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/tv.pluto.android"

