[youtube-anddea-nord]
enabled = true
app-name = "youtube"
rv-brand = "anddea-nord"
build-mode = "both"
arch = "both"
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-desktop"
included-patches = "'MaterialYou'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#2E3440 -OlightThemeBackgroundColor=#E5E9F0"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-music-anddea-nord]
enabled = true
app-name = "youtube-music"
rv-brand = "anddea-nord"
build-mode = "both"
arch = "both"
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-desktop"
patcher-args = "-e 'Dark theme' -OdarkThemeBackgroundColor=#2E3440 -OmaterialYou=#5E81AC"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[youtube-anddea-mocha]
enabled = true
app-name = "youtube"
rv-brand = "anddea-mocha"
build-mode = "both"
arch = "both"
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-desktop"
included-patches = "'MaterialYou'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#FF181825 -OlightThemeBackgroundColor=#E6E9EF"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-music-anddea-mocha]
enabled = true
app-name = "youtube-music"
rv-brand = "anddea-mocha"
build-mode = "both"
arch = "both"
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-desktop"
patcher-args = "-e 'Dark theme' -OdarkThemeBackgroundColor=#FF181825 -OmaterialYou=#89B4FA"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[reddit-anddea]
enabled = false
app-name = "reddit"
rv-brand = "anddea"
build-mode = "apk"
arch = "both"
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"

