[telegram-revanced-gplay]
enabled = true
app-name = "telegram"
rv-brand = "revanced-gplay"
build-mode = "apk"
arch = "both"
patches-source = "Aunali321/ReVancedExperiments"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://telegram-google-play-version.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/telegram-fz-llc/telegram"
dpi = "nodpi anydpi auto"

[telegram-revanced-foss]
enabled = true
app-name = "telegram"
rv-brand = "revanced-foss"
build-mode = "apk"
arch = "both"
patches-source = "Aunali321/ReVancedExperiments"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://telegram.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/telegram-fz-llc/telegram-web-version"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/org.telegram.messenger"

[instagram-revanced-exp]
enabled = true
app-name = "instagram"
rv-brand = "revanced-exp"
build-mode = "apk"
arch = "both"
patches-source = "Aunali321/ReVancedExperiments"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/com.instagram.android"

