[automate-morphe]
enabled = true
app-name = "automate"
rv-brand = "morphe"
build-mode = "both"
arch = "both"
patches-source = "BholeyKaBhakt/revanced-patches-xtra"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://automate-beta.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/llamalab/automate-llamalab"
dpi = "nodpi anydpi auto"

[speedtest-morphe]
enabled = true
app-name = "speedtest"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "BholeyKaBhakt/revanced-patches-xtra"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://speedtest-net-mobile.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/ookla/speedtest"
dpi = "nodpi anydpi auto"

[autosync-morphe]
enabled = true
app-name = "autosync"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "BholeyKaBhakt/revanced-patches-xtra"
# patcher-args = "--continue-on-error"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://autosync.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/metactrl/autosync-universal-cloud-sync-and-backup"
dpi = "nodpi anydpi auto"

[inshorts-morphe]
enabled = true
app-name = "inshorts"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "BholeyKaBhakt/revanced-patches-xtra"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://inshorts.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/inshorts-formerly-news-in-shorts/inshorts-news-in-60-words-2"
dpi = "nodpi anydpi auto"

