[pinterest-morphe]
enabled = true
app-name = "pinterest"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "binarymend/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://pinterest.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pinterest/pinterest-one-destination-for-a-world-of-inspiration"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.pinterest"

[moonplus-reader-morphe]
enabled = true
app-name = "moonplus-reader"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "binarymend/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://moon-reader.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/moon/moon-reader"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.photos"

[symfonium-morphe]
enabled = true
app-name = "symfonium"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "binarymend/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://symfonium.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tolriq/symfonium-music-player-cast"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/app.symfonik.music.player"

[calcnote-morphe]
enabled = true
app-name = "calcnote"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "binarymend/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://calcnote-notepad-calculator.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/burton999/calcnote-notepad-calculator"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.photos"

[acalendar-morphe]
enabled = true
app-name = "acalendar"
rv-brand = "morphe"
build-mode = "apk"
arch = "all"
patches-source = "binarymend/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://acalendar.en.uptodown.com/android"
dpi = "nodpi anydpi auto"
apkpure-dlurl = "https://apkpure.com/acalendar-your-calendar/org.withouthat.acalendar"

