[google-news-morphe]
enabled = true
app-name = "google-news"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "docbt/patched-up"
# patcher-args = "--continue-on-error"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://google-play-newsstand.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-news/"
dpi = "nodpi anydpi auto"

[facebook-morphe]
enabled = true
app-name = "facebook"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "MeridianFresco/morphe-meta-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.facebook.katana"

[trakt-morphe]
enabled = true
app-name = "trakt"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "IMXEren/mix-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://trakt.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/trakt/trakt"
dpi = "nodpi anydpi auto"
# archive-dlurl = ""

[cryptomator-morphe]
enabled = true
app-name = "cryptomator"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "joganubaid/cryptomator-morphe-patches"
cli-source = "MorpheApp/morphe-cli"
direct-dlurl = "https://static.cryptomator.org/android/1.12.3/Cryptomator-1.12.3.apk"

[komoot-morphe]
enabled = true 
app-name = "komoot"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "brosssh/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/komoot-gmbh/komoot-cycling-hiking-mountain-biking-maps"
uptodown-dlurl = "https://komoot.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/komoot-hike-bike-run/de.komoot.android"

[discord-xposed]
enabled = true 
app-name = "discord"
rv-brand = "xposed"
build-mode = "apk"
arch = "all"
patches-source = "revenge-mod/revenge-xposed"
cli-source = "7723mod/NPatch"
dpi = "nodpi anydpi auto"
uptodown-dlurl = "https://discord-chat-for-gamers.en.uptodown.com/android"
apkcombo-dlurl = "https://apkcombo.com/discord/com.discord/"

[microsoft-edge-morphe]
enabled = true
app-name = "microsoft-edge"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
version = "148.0.3967.97"
patches-source = "quantavil/edge-morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://microsoft-edge.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/microsoft-corporation/microsoft-edge"
dpi = "nodpi anydpi auto"
# archive-dlurl = ""