[adguard-morphe-nightly]
enabled = true
app-name = "adguard"
rv-brand = "morphe-nightly"
build-mode = "both"
arch = "both"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://adguard-for-android.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adguard-software-limited/adguard"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[waze-morphe]
enabled = true
app-name = "waze"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://waze.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/waze/waze-gps-maps-traffic-alerts-live-navigation"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/tv.twitch.android.app"

[warp-morphe]
enabled = true
app-name = "warp"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://1-1-1-1.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/cloudflare/1-1-1-1-faster-safer-internet"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/tv.twitch.android.app"


[hola-vpn-morphe]
enabled = true 
app-name = "hola-vpn"
rv-brand = "morphe"
build-mode = "apk"
arch = "arm64-v8a"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
dpi = "nodpi anydpi auto"
uptodown-dlurl = "https://holavpn.en.uptodown.com/android"
apkpure-dlurl = "https://m.apkpure.com/hola-vpn-proxy-plus/org.hola.prem"

[ninja-vpn-morphe]
enabled = true 
app-name = "ninja-vpn"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
dpi = "nodpi anydpi auto"
apkpure-dlurl = "https://apkpure.com/ninja-vpn-fast-secure-vpn/app.ninjavpn.android"
uptodown-dlurl = "https://ninja-vpn.uptodown.com/android"
apkcombo-dlurl = "https://apkcombo.com/ninja-vpn-fast-secure-vpn/app.ninjavpn.android"

[windscribe-vpn-morphe]
enabled = true 
app-name = "windscribe-vpn"
rv-brand = "morphe"
build-mode = "apk"
arch = "all"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/windscribe/windscribe-vpn"
uptodown-dlurl = "https://windscribe.uptodown.com/android"
apkcombo-dlurl = "https://apkcombo.com/windscribe/com.windscribe.vpn"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.windscribe.vpn"

[terabox-morphe]
enabled = true 
app-name = "terabox"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/flextech-inc/terabox-cloud-storage-cloud-backup-data-backup"
uptodown-dlurl = "https://terabox.en.uptodown.com/android"

[all-document-reader-morphe]
enabled = true
app-name = "all-document-reader"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://all-documents-reader.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/bucket-of-apps/all-documents-reader-documents-viewer"
dpi = "nodpi anydpi auto"
# archive-dlurl = ""

[accuweather-morphe]
enabled = true
app-name = "accuweather"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://accuweather.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/accuweather/accuweather"
dpi = "nodpi anydpi auto"
# archive-dlurl = ""

[the-weather-channel-morphe]
enabled = true
app-name = "the-weather-channel"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://the-weather-channel.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/the-weather-channel/the-weather-channel-local-forecast-weather-maps"
dpi = "nodpi anydpi auto"
# archive-dlurl = ""

[beta-maniac-morphe]
enabled = true
app-name = "beta-maniac"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://beta-maniac.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/mirko-dimartino/beta-maniac-life-of-a-beta-tester-2"
dpi = "nodpi anydpi auto"
# archive-dlurl = ""




