enable-module-updates = true
parallel-jobs = 1
patches-version = "dev"

[amazon-india]
enabled = true
app-name = "com.amazon.mShop.android.shopping"
rv-brand = "none"
build-mode = "apk"
patches-source = "none"
patches-source-host = "none"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://amazon-india.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-india-shop-pay/"
dpi = "nodpi anydpi auto"
