[x-shim]
enabled = true 
app-name = "x-shim"
rv-brand = "shim"
build-mode = "apk"
patches-source = "crimera/x-shim"
patches-source-host = "gitlab"
patcher-args = "--continue-on-error"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/geologically/apks/com.twitter.android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"