name: Cleanup Container
description: Cleanup Container
runs:
  using: "composite"
  steps:
    - name: Stop FlareSolverr
      shell: bash
      run: |
        docker logs flaresolverr || true
        docker rm --force flaresolverr || true
    - name: Stop Byparr
      if: false
      shell: bash
      run: |
        docker logs byparr || true
        docker rm --force byparr || true
    - name: Stop CloudflareBypassForScraping
      shell: bash
      run: |
        docker logs cloudflarebypass || true
        docker rm --force cloudflarebypass || true