name: Cleanup Container
description: Cleanup Container
runs:
  using: "composite"
  steps:
    - name: Stop Redis
      shell: bash
      run: |
        docker logs redis || true
        docker rm --focre redis || true
    - name: Stop Trawl
      shell: bash
      run: |
        docker logs Trawl || true
        docker rm --force Trawl || true