name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_run:
    workflows: ["Update Releases Cache"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages

  trigger_notify_failure:
    needs: [ deploy ]
    if: failure()
    uses: ./.github/workflows/notify.yml
    with:
      workflow_name: "Deploy to GitHub Pages"
    secrets: inherit
