name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_run:
    workflows: ["Update Releases Cache"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: '.'

      - name: Deploy to GitHub Pages (with Retries)
        id: deployment
        uses: Wandalen/wretry.action@v3.5.0
        with:
          action: actions/deploy-pages@v4
          attempt_limit: 3
          attempt_delay: 10000 # Wait 10 seconds between retries

  trigger_notify_failure:
    needs: [ deploy ]
    if: failure()
    uses: ./.github/workflows/notify.yml
    with:
      workflow_name: "Deploy to GitHub Pages"
    secrets: inherit
