name: "[Auto] Nightly Builds"

on:
  # schedule:
  #   # every day at 6 pm
  #   - cron: "0 18 * * *"
  workflow_dispatch:

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      devel: false
      build-id: 'nightly'
    secrets: inherit

  release:
    name: "Create Release"
    needs: [build]
    if: ${{ always() }}
    permissions:
      actions: read
      security-events: write
      contents: write
      discussions: write
    uses: ./.github/workflows/release.yml
    with:
      devel: false
      build-id: 'nightly'
      status: ${{ needs.build.result }}
    secrets: inherit