name: "[Manual] Workflow PR"

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
  schedule:
    - cron: "0 2/4 * * *"

    
env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}

jobs:
  build:
    name: Build
    concurrency:
      group: test-build-${{ github.ref_name }}
      cancel-in-progress: true
    uses: ./.github/workflows/build.yml
    with:
      devel: true
      build-id: 'test'
    secrets: inherit

  release:
    name: "Create Release"
    needs: [build]
    if: ${{ always() }}
    permissions:
      actions: read
      security-events: write
      contents: write
      discussions: write
    uses: ./.github/workflows/release.yml
    with:
      devel: true
      build-id: 'test'
      status: ${{ needs.build.result }}
    secrets: inherit
